// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOgr9pHDfxksA96bq1i6l0HFvt9tMNdOg',
    appId: '1:810266796578:web:4a5bdc68a54fe32491207b',
    messagingSenderId: '810266796578',
    projectId: 'iprakriti',
    authDomain: 'iprakriti.firebaseapp.com',
    storageBucket: 'iprakriti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtBPtFRxZ6MxZlKlsny93ygIrGNa0vFU',
    appId: '1:810266796578:android:ff96ac454f85140291207b',
    messagingSenderId: '810266796578',
    projectId: 'iprakriti',
    storageBucket: 'iprakriti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgE-4oQ1yDJYz4THkg3E3AcicZ3xPYC8',
    appId: '1:810266796578:ios:95d12ced2790f50f91207b',
    messagingSenderId: '810266796578',
    projectId: 'iprakriti',
    storageBucket: 'iprakriti.appspot.com',
    iosBundleId: 'com.example.iprakriti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgE-4oQ1yDJYz4THkg3E3AcicZ3xPYC8',
    appId: '1:810266796578:ios:273b568cead9761791207b',
    messagingSenderId: '810266796578',
    projectId: 'iprakriti',
    storageBucket: 'iprakriti.appspot.com',
    iosBundleId: 'com.example.iprakriti.RunnerTests',
  );
}
